package models

import (
	"github.com/jinzhu/gorm"
)

type Galleries struct {
	gorm.Model
	UserID uint    `gorm:"not_null;index"`
	Title  string  `gorm:"not_null"`
	Images []Image `gorm:"-"`
}

func (g *Galleries) ImagesSplitN(n int) [][]Image {
	// Create a 2D slice
	ret := make([][]Image, n)
	// Create inner slices
	for i := 0; i < n; i++ {
		ret[i] = make([]Image, 0)
	}
	// Populate ret
	for i, img := range g.Images {
		bucket := i % n
		ret[bucket] = append(ret[bucket], img)
	}
	return ret
}

// GalleryDB is used to interact with the galleries' database.
//
// For pretty much all single gallery queries:
// If the gallery is found, it will return a nil error
// If the gallery is no found, it will return ErrNotFound
// If there is another error, it will return an error with more information about what went wrong.
// This may not be an error generated by the models packages.
type GalleryDB interface {
	ByID(id uint) (*Galleries, error)
	ByUserID(userID uint) ([]Galleries, error)
	Create(gallery *Galleries) error
	Update(gallery *Galleries) error
	Delete(id uint) error
}

type galleryGorm struct {
	db *gorm.DB
}

type GalleryService interface {
	GalleryDB
}

type galleryService struct {
	GalleryDB
}

type galleryValidator struct {
	GalleryDB
}

func NewGalleryService(db *gorm.DB) GalleryService {
	return &galleryService{
		GalleryDB: &galleryValidator{
			GalleryDB: &galleryGorm{
				db: db,
			},
		},
	}
}

type galleryValFn func(*Galleries) error

func runGalleryValFns(gallery *Galleries, fns ...galleryValFn) error {
	for _, fn := range fns {
		if err := fn(gallery); err != nil {
			return err
		}
	}
	return nil
}

func (gg *galleryGorm) ByID(id uint) (*Galleries, error) {
	var gallery Galleries
	db := gg.db.Where("id = ?", id)
	err := first(db, &gallery)
	if err != nil {
		return nil, err
	}
	return &gallery, nil
}

func (gg *galleryGorm) ByUserID(userID uint) ([]Galleries, error) {
	var galleries []Galleries
	db := gg.db.Where("user_id = ?", userID)
	if err := db.Find(&galleries).Error; err != nil {
		return nil, err
	}
	return galleries, nil
}

func (gv *galleryValidator) userIDRequired(g *Galleries) error {
	if g.UserID <= 0 {
		return ErrUserIDRequired
	}
	return nil
}

func (gv *galleryValidator) titleRequired(g *Galleries) error {
	if g.Title == "" {
		return ErrTitleRequired
	}
	return nil
}

func (gv *galleryValidator) Create(gallery *Galleries) error {
	err := runGalleryValFns(gallery,
		gv.userIDRequired,
		gv.titleRequired)
	if err != nil {
		return err
	}
	return gv.GalleryDB.Create(gallery)
}

func (gg *galleryGorm) Create(gallery *Galleries) error {
	return gg.db.Create(gallery).Error
}

func (gv *galleryValidator) Update(gallery *Galleries) error {
	err := runGalleryValFns(gallery,
		gv.userIDRequired,
		gv.titleRequired)
	if err != nil {
		return err
	}
	return gv.GalleryDB.Update(gallery)
}

func (gg *galleryGorm) Update(gallery *Galleries) error {
	return gg.db.Save(gallery).Error
}

func (gv *galleryValidator) nonZeroID(gallery *Galleries) error {
	if gallery.ID <= 0 {
		return ErrIDInvalid
	}
	return nil
}

func (gv *galleryValidator) Delete(id uint) error {
	var gallery Galleries
	gallery.ID = id
	if err := runGalleryValFns(&gallery, gv.nonZeroID); err != nil {
		return err
	}
	return gv.GalleryDB.Delete(gallery.ID)
}

func (gg *galleryGorm) Delete(id uint) error {
	gallery := &Galleries{
		Model: gorm.Model{ID: id},
	}
	return gg.db.Delete(gallery).Error
}
